# Generated by Django 4.1.7 on 2023-04-04 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='numero',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
